const imgUrl = process.env.NEXT_PUBLIC_CDN;
const speakerList = [
  {
    fname: "Nuwan",
    lname: "Kaushalya ",
    position: "Lead Engineer - Technical Support",
    company: "Persistent Systems ",
    linkedin: " https://www.linkedin.com/in/nuwankaushalya/",
    picture: `${imgUrl}/images/summit25/speaker/nuwan.webp`,
  },
  {
    fname: "Anjana ",
    lname: "Dodampe",
    position: "Senior Software Engineer",
    company: "London Stock Exchange Group",
    linkedin: "https://www.linkedin.com/in/anjanadodampe/",
    picture: `${imgUrl}/images/summit25/speaker/anjana.webp`,
  },
  {
    fname: "Sachithra",
    lname: "Manamperi",
    position: "DevOps Engineer",
    company: "Insighture",
    linkedin: "https://www.linkedin.com/in/sachithra-manamperi-4a93851a5/",
    picture: `${imgUrl}/images/summit25/speaker/sachithra.webp`,
  },
  {
    fname: "Pasan",
    lname: "Devin Jayawardene",
    position: "Software Engineer - AI/R&D",
    company: "Insighture",
    linkedin: "https://www.linkedin.com/in/pasandevin/",
    picture: `${imgUrl}/images/summit25/speaker/pasan.webp`,
  },
  {
    fname: "Hansamali",
    lname: "Gamage",
    position: "Senior Developer",
    company: "NEXT",
    linkedin: "https://www.linkedin.com/in/hansamali-gamage/",
    picture: `${imgUrl}/images/summit25/speaker/hansamali.webp`,
  },
  {
    fname: "Kavimal ",
    lname: "Wijewardana",
    position: "Associate Architect - Mobile",
    company: "Virtusa Corp.",
    linkedin: " https://www.linkedin.com/in/kavimal-wijewardana/",
    picture: `${imgUrl}/images/summit25/speaker/kavimal.webp`,
  },
  {
    fname: "Nikila",
    lname: "Fernando",
    position: "DevOps Engineer",
    company: "Fortude",
    linkedin: "https://www.linkedin.com/in/nikilafernando99/",
    picture: `${imgUrl}/images/summit25/speaker/nikila.webp`,
  },
  {
    fname: "Joy",
    lname: "Rathnayake",
    position: "Associate Director/Solutions Architect",
    company: "WSO2",
    linkedin: "https://www.linkedin.com/in/joyrathnayake/",
    picture: `${imgUrl}/images/summit25/speaker/joy.webp`,
  },
  {
    fname: "Asma",
    lname: "Muzammil",
    position: "QA Lead",
    company: "Code94 Labs",
    linkedin: "https://www.linkedin.com/in/asmamuzammil/",
    picture: `${imgUrl}/images/summit25/speaker/asma.webp`,
  },
  {
    fname: "Buddima",
    lname: "Udaranga",
    position: "Lead platform engineer",
    company: "Codification",
    linkedin: "https://www.linkedin.com/in/buddhima-udaranga/",
    picture: `${imgUrl}/images/summit25/speaker/buddima.webp`,
  },
];

export default speakerList;
